### ISSUE TITLE
fetch_user': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

### ISSUE THREAD

**Issue by ccamacho** [Patreon/patreon-ruby#19]
I'm trying to sum all the historical pledges from all my patrons to create a pledges ranking, I'm following the README.md[1] file but it does not work, this is the error I'm getting:

fetch_user': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

[1]: https://github.com/Patreon/patreon-ruby/blob/master/README.md

**Comment by jrsun** [comment]
as far as i can tell, the readme seems to be wrong! the source code shows that `fetch_user` expects a single hash as argument! https://github.com/Patreon/patreon-ruby/blob/master/lib/patreon/api.rb#L7-L9
